export const SEASON_REQUEST = "SEASON_REQUEST";
export const SEASON_FAILURE = "SEASON_FAILURE";

export const CREATE_SEASON_SUCCESS = "CREATE_SEASON_SUCCESS";
export const GET_ALL_SEASONS_SUCCESS = "GET_ALL_SEASONS_SUCCESS";
