
// Define action types for movie actions
export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_FAILURE = "MOVIE_FAILURE";

export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIES_BY_IDS_SUCCESS = "GET_MOVIES_BY_IDS_SUCCESS";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
