// src/Redux/EpisodeReducer/ActionTypes.js
export const EPISODE_REQUEST = "EPISODE_REQUEST";
export const EPISODE_FAILURE = "EPISODE_FAILURE";
export const CREATE_EPISODE_SUCCESS = "CREATE_EPISODE_SUCCESS";
export const GET_ALL_EPISODES_SUCCESS = "GET_ALL_EPISODES_SUCCESS";
