
server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: false

      routes:
        # Authentication service route
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # User service route
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user/**

        # Video service route
        - id: video-service-route
          uri: lb://video-service
          predicates:
            - Path=/video/**


        - id: video-service-route
          uri: lb://video-service
          predicates:
            - Path=/movies/**

        # Rating and recommendation service route
        - id: rating_and_recommendation-service-route
          uri: lb://rating-and-recommendation
          predicates:
            - Path=/recommendation/**

