server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: false
      
      routes:

        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: video-service-route
          uri: lb://video-service
          predicates:
            - Path=/video/**
            - Path=/episodes/**
            - Path=/series/**
            - Path=/seasons/**

        - id: rating_and_recommendation-service-route
          uri: lb://rating_and_recommendation-service
          predicates:
            - Path=/rating/**
