
// Define action types for video actions
export const VIDEO_REQUEST = "VIDEO_REQUEST";
export const VIDEO_FAILURE = "VIDEO_FAILURE";

export const CREATE_VIDEO_SUCCESS = "CREATE_VIDEO_SUCCESS";
export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const STREAM_VIDEO_SUCCESS = "STREAM_VIDEO_SUCCESS";
export const GET_THUMBNAIL_SUCCESS = "GET_THUMBNAIL_SUCCESS";
export const GET_VIDEOS_BY_IDS_SUCCESS = "GET_VIDEOS_BY_IDS_SUCCESS";
export const RECOMMENDATION_REQUEST = "RECOMMENDATION_REQUEST";
export const RECOMMENDATION_SUCCESS = "RECOMMENDATION_SUCCESS";
export const RECOMMENDATION_FAILURE = "RECOMMENDATION_FAILURE";