export const SERIES_REQUEST = "SERIES_REQUEST";
export const SERIES_FAILURE = "SERIES_FAILURE";

export const CREATE_SERIES_SUCCESS = "CREATE_SERIES_SUCCESS";
export const GET_ALL_SERIES_SUCCESS = "GET_ALL_SERIES_SUCCESS";
