
//for Login Reqiuest
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"



export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"

export const POST_SIGN_SUCCESS="POST_SIGN_SUCCESS"

export const MYSPACE_UPDATE="MYSPACE_UPDATE"